import assert from 'node:assert/strict';
import {compactReferenceMessage as compact,savedReferenceDisplayMetadata as metadata} from '../web/prompt-reference-display.js';
let checked=0;
function check(actual,expected) {assert.equal(actual,expected);checked++;}
check(compact('普通输入 unchanged'),'普通输入 unchanged');
check(compact('把【参考图1】 [[image:a]] 和【点1】 [[annotation:b]]比较。'),'把【参考图1】 和【点1】比较。');
check(compact('【参考图1】\t[[image:a]]'),'【参考图1】');
check(compact('【参考图1】\n[[image:a]]'),'【参考图1】\n【图片1】');
check(compact('before [[image:a]] after [[image:a]] / [[image:b]]'),'before 【图片1】 after 【图片1】 / 【图片2】');
check(compact('原始说明 保持自由文字 [[object:long-internal-id]]'),'原始说明 保持自由文字 【物体1】');
check(compact('请改 [[image:abc123'),'请改 【图片1】');
check(compact('用户 [[other:unchanged]]'),'用户 [[other:unchanged]]');
check(compact('old [[image:a]] and 【图片1】 [[image:b]]'),'old 【图片2】 and 【图片1】');
const image=[{token:'[[image:a]]',kind:'image',image:{pane:'reference',label:'参考图 · very-long-filename.png'}}];
check(compact('参考图 · very-long-filename.png [[image:a]] 请对齐',image),'【参考图1】 请对齐');
check(compact('不要删用户说明 [[image:a]]',image),'不要删用户说明 【参考图1】');
check(compact('参考图 · very-long-filename.png [[image:a]]',{bad:true}),'参考图 · very-long-filename.png 【图片1】');
const objects=[{token:'[[object:a]]',object:{name:'柜子'}},{token:'[[object:b]]',object:{name:'柜子'}}];
check(compact('柜子 [[object:a]] 柜子 [[object:b]]',objects),'【柜子】 【柜子2】');
check(compact('小柜子 [[object:a]]',objects),'小柜子 【柜子】');
check(compact('柜子（往左移） [[object:a]]',objects),'柜子（往左移） 【柜子】');
check(compact('部件 with long filename [[node:o:0/2]]',[{token:'[[node:o:0/2]]',scene_node:{node_name:'部件 with long filename'}}]),'【部件 with long fi…】');
const feedback={inline_references:[{token:'[[annotation:a]]',annotation:{name:'点1',pane:'scene',snapshot_id:'s'}}],scene_snapshots:[{id:'s',name:'厨房透视图'}]};
check(compact('点1（厨房透视图） [[annotation:a]] 请移近',metadata(feedback)),'【点1】 请移近');
const refFeedback={inline_references:[{token:'[[annotation:a]]',annotation:{name:'点1',pane:'reference',reference_image_id:'r'}}],reference_images:[{id:'r',name:'原始照片.jpeg'}]};
check(compact('点1（参考图 原始照片.jpeg） [[annotation:a]]',metadata(refFeedback)),'【点1】');
const video={inline_references:[{token:'[[annotation:a]]',annotation:{name:'线2',pane:'scene',frame_id:'f',time_sec:.5,frame_index:15,view_name:'前方'}}]};
check(compact('线2（机位 前方 · 片段第 16 帧 · 0.500 s） [[annotation:a]]',metadata(video)),'【线2】');
check(compact('[[pose:abc:def]] [[pose_edit:abc]]'),'【人体1】 【手部修正1】');
check(compact('a '.repeat(300)+'[[image:abc]]'),'a '.repeat(300)+'【图片1】');
check(compact(null),'');
assert.deepEqual(feedback.inline_references[0],{token:'[[annotation:a]]',annotation:{name:'点1',pane:'scene',snapshot_id:'s'}});checked++;
const icon=(text,refs=[])=>compact(text,refs,{icons:true});
check(icon('改🧊1 [[object:a]]，看🖼️1 [[image:a]]与🧩1 [[node:o:0/2]]。'),'改🧊1，看🖼️1与🧩1。');
check(icon('改【物体8】 [[object:a]]与【柜子】 [[object:b]]；【图片2】 [[image:a]]'),'改🧊8与🧊1；🖼️2');
check(icon('old [[image:a]] and 🖼️1 [[image:b]] then [[image:a]]'),'old 🖼️2 and 🖼️1 then 🖼️2');
check(icon('柜子 [[object:a]] 柜子 [[object:b]]',objects),'🧊1 🧊2');
check(icon('普通说明【其他】保持；🕒1 片段0.100000001s'),'普通说明【其他】保持；🕒1 片段0.100000001s');
check(icon('【时间戳3】 片段0.100000001s'),'🕒3 片段0.100000001s');
console.log(`${checked} reference display checks passed`);
